env = Environment()
env.Append(CCFLAGS = ['-g', '-Wall', '-ansi', '-pedantic', '-Wextra', '-fmessage-length=0'])
env.Append(LIBS = ['GLEW', 'glfw' ,'GL', 'GLU', 'fmodex', 'SOIL', 'boost_program_options'])
env.Program('mengine', Glob('*.cpp'))
