env = Environment()
env.Append(CCFLAGS = ['-g', '-O', '-Wall', '-ansi', '-pedantic', '-Wextra', '-fmessage-length=0' ])
env.Append(LIBS = ['GLEW', 'glfw' ,'GL', 'GLU', 'SOIL'])
env.Program('mengine', Glob('*.cpp'))
